/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as BookRouteImport } from './routes/book'
import { Route as ChauffeurServiceHarareRouteImport } from './routes/chauffeur-service-harare'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as DiasporaRouteImport } from './routes/diaspora'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SelfDriveCarHireHarareRouteImport } from './routes/self-drive-car-hire-harare'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminDriversRouteImport } from './routes/admin/drivers'
import { Route as AdminFleetRouteImport } from './routes/admin/fleet'
import { Route as AdminInquiriesRouteImport } from './routes/admin/inquiries'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPricingRouteImport } from './routes/admin/pricing'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminToursRouteImport } from './routes/admin/tours'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeurServiceHarareRoute = ChauffeurServiceHarareRouteImport.update({
  id: '/chauffeur-service-harare',
  path: '/chauffeur-service-harare',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DiasporaRoute = DiasporaRouteImport.update({
  id: '/diaspora',
  path: '/diaspora',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SelfDriveCarHireHarareRoute = SelfDriveCarHireHarareRouteImport.update({
  id: '/self-drive-car-hire-harare',
  path: '/self-drive-car-hire-harare',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminToursRoute = AdminToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/chauffeur-service-harare': typeof ChauffeurServiceHarareRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/diaspora': typeof DiasporaRoute
  '/fleet': typeof FleetRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/self-drive-car-hire-harare': typeof SelfDriveCarHireHarareRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tours': typeof ToursRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/chauffeur-service-harare': typeof ChauffeurServiceHarareRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/diaspora': typeof DiasporaRoute
  '/fleet': typeof FleetRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/self-drive-car-hire-harare': typeof SelfDriveCarHireHarareRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tours': typeof ToursRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/chauffeur-service-harare': typeof ChauffeurServiceHarareRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/diaspora': typeof DiasporaRoute
  '/fleet': typeof FleetRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/self-drive-car-hire-harare': typeof SelfDriveCarHireHarareRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/tours': typeof ToursRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tours': typeof AdminToursRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/book'
    | '/chauffeur-service-harare'
    | '/contact'
    | '/cookie-policy'
    | '/diaspora'
    | '/fleet'
    | '/privacy-policy'
    | '/self-drive-car-hire-harare'
    | '/terms-of-service'
    | '/tours'
    | '/admin/audit-log'
    | '/admin/bookings'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/documents'
    | '/admin/drivers'
    | '/admin/fleet'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/tours'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/chauffeur-service-harare'
    | '/contact'
    | '/cookie-policy'
    | '/diaspora'
    | '/fleet'
    | '/privacy-policy'
    | '/self-drive-car-hire-harare'
    | '/terms-of-service'
    | '/tours'
    | '/admin/audit-log'
    | '/admin/bookings'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/documents'
    | '/admin/drivers'
    | '/admin/fleet'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/tours'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/book'
    | '/chauffeur-service-harare'
    | '/contact'
    | '/cookie-policy'
    | '/diaspora'
    | '/fleet'
    | '/privacy-policy'
    | '/self-drive-car-hire-harare'
    | '/terms-of-service'
    | '/tours'
    | '/admin/audit-log'
    | '/admin/bookings'
    | '/admin/content'
    | '/admin/customers'
    | '/admin/documents'
    | '/admin/drivers'
    | '/admin/fleet'
    | '/admin/inquiries'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/reports'
    | '/admin/staff'
    | '/admin/tours'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  ChauffeurServiceHarareRoute: typeof ChauffeurServiceHarareRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DiasporaRoute: typeof DiasporaRoute
  FleetRoute: typeof FleetRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SelfDriveCarHireHarareRoute: typeof SelfDriveCarHireHarareRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ToursRoute: typeof ToursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeur-service-harare': {
      id: '/chauffeur-service-harare'
      path: '/chauffeur-service-harare'
      fullPath: '/chauffeur-service-harare'
      preLoaderRoute: typeof ChauffeurServiceHarareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diaspora': {
      id: '/diaspora'
      path: '/diaspora'
      fullPath: '/diaspora'
      preLoaderRoute: typeof DiasporaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/self-drive-car-hire-harare': {
      id: '/self-drive-car-hire-harare'
      path: '/self-drive-car-hire-harare'
      fullPath: '/self-drive-car-hire-harare'
      preLoaderRoute: typeof SelfDriveCarHireHarareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tours': {
      id: '/admin/tours'
      path: '/tours'
      fullPath: '/admin/tours'
      preLoaderRoute: typeof AdminToursRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminFleetRoute: typeof AdminFleetRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminToursRoute: typeof AdminToursRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminFleetRoute: AdminFleetRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminToursRoute: AdminToursRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  ChauffeurServiceHarareRoute: ChauffeurServiceHarareRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DiasporaRoute: DiasporaRoute,
  FleetRoute: FleetRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SelfDriveCarHireHarareRoute: SelfDriveCarHireHarareRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ToursRoute: ToursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
